apiVersion: v1

kind: Service

metadata:

  name: nodeport-wp

spec:

  type: NodePort

  selector:

    app_name: mywp

  ports:

  - nodePort: 32410

    protocol: TCP

    port: 80

    targetPort: 80
