apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  revisionHistoryLimit: 3
  replicas: 10
  selector:
    matchLabels:
      app_name: myredis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
      # maxSurge: 25%
      # maxUnavailable: 25%
  template:
    metadata:
      labels:
        app_name: myredis
    spec:
      containers:
      - name: redis
        image: redis:7
        # image: redis:7
        ports:
        - containerPort: 80
# change something
# reapply
# show the rollout history
# kubectl rollout history deployment/redis-deployment --revision=2

#strategy
#https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy

# scale
# kubectl scale deployment/redis-deployment --replicas=10

#show in 2 terminals
