apiVersion: batch/v1
kind: Job
metadata:
  name: say-something
spec:
  completions: 5
  template:
    metadata:
      name: say-something
    spec:
      containers:
      - name: say-something
        image: busybox
        command: ["echo", "Running a job."]
      restartPolicy: OnFailure

# Show example

# Apply

# Show the log of the job

# k logs job/say-something                                                                                                                                                                     130 ↵
# Found 5 pods, using pod/say-something-lg5sh
# Running a job
